
unbind = , Print
unbind = Super+Shift, W
unbind = Super, mouse_down
unbind = Super, mouse_up
unbind = Super, B

bindl = , Print, global, caelestia:screenshotFreeze  # Capture region (freeze)

bind = Super+Shift, W, exec, caelestia wallpaper --random ~/Pictures/Wallpapers/
bind = Super, mouse_down, workspace, +1
bind = Super, mouse_up, workspace, -1
bind = Super, B, exec, [fullscreen_state 0 2] app2unit -- firefox

gesture = $workspaceSwipeFingers, pinch, dispatcher fullscreenstate 2 0 toggle

# !!!
windowrule = float, class:foot
windowrule = size 40% 40%, class:foot
windowrule = center 1, class:foot



